### ISSUE TITLE
How to connect the Broker server in MQTT client packages

### ISSUE THREAD

**Issue by GarettShi** [LabVIEW-Open-Source/MQTT-Client#10]
Hello Francois, firstly thanks for your share MQTT client package. 
I have learned much from your code. But I have a question about how to connect a remote broker server. There is no Broker server address set argument for the input arguments in the sub VI '_**Connect to server.vi**_' , only has clusters '_Connect flags_' and '_Payload_'. So how to set this borker server? 
I'm looking forword your replay, and my email: Garett@foxmail.com
Again, thank you for your work.

GarettShi

**Comment by francois-normandin** [comment]
Hi @GarettShi ,

The connection configuration is injected in the client's constructor. It's a way to abstract the transport layer from the MQTT protocol.

There is some useful information, including YouTube video, in the MQTT broker project's wiki pages:
https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker/wiki#walkthrough-presentations

In the YouTube presentation, you'll see an example of what you need around 7min from the start.

Best,
François

**Comment by GarettShi** [comment]
Thanks so much for your replay, I have watched the video and got it. I have to say that your open source is very great. Wish you have more great open source, I willl follow and be your biggest fan.

**Comment by francois-normandin** [comment]
Thanks for your kind words @GarettShi 
I`ll be closing this issue now.
