### ISSUE TITLE
Loosing Network Connection

### ISSUE THREAD

**Issue by ssummers-lime** [LabVIEW-Open-Source/MQTT-Client#12]
While trying to publish data with QoS 0 using TCP, if the network connection is lost then the main application is not notified of the lost connection.  When the write vi is called, an error is generated from the TCP write and is passed into the setConnected.vi. Since this vi has an error case to capture incoming errors, the lose of connection is never set.  A quick fix would be to remove the case structure.  The vi also generates a user event "connection event" but I did not find this event being registered anywhere.

![image](https://user-images.githubusercontent.com/60670718/160643273-4d0e7f24-ecac-428a-8aa5-d9f36bca71b5.png)

![image](https://user-images.githubusercontent.com/60670718/160644140-9fbb56ef-325f-4df3-9ef7-c20a2ed6f22b.png)

**Comment by francois-normandin** [comment]
@ssummers-lime 
Thanks for this report. You are correct and the error case structure should be removed to allow the code to execute even with an upstream error.
I'll reference this bug in the MQTT-Connection repo for action.

**Comment by francois-normandin** [comment]
This is fixed and released in MQTT_Connection package 3.1.4.
Will show up on vipm.io shortly.
