### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by T81** [LabVIEW-Open-Source/MQTT-Client#21]
Is there support for secure connections using a ca certificate under LabVIEW 2019?

**Comment by francois-normandin** [comment]
No there is not. LabVIEW did not natively support TLS before version 2020.

But it is possible to provide support by writing an extension with .net calls, based on the model of this project:

https://github.com/LabVIEW-Open-Source/MQTT-Connection-SecuredTCP

Copy the project, rename the libraries, replace the TLS calls in this project with .NET and back save. That would technically provide TLS support all the way back to 2013.

**Comment by T81** [comment]
How about LabVIEW 2022?

**Comment by francois-normandin** [comment]
Yes, the package mentioned above will work for LabVIEW 2020 and above.
