### ISSUE TITLE
Password in connect packet is not UTF8 encoded

### ISSUE THREAD

**Issue by joerghampel** [LabVIEW-Open-Source/MQTT-Client#3]
I'm trying to connect to an ActiveMQ broker, which requires username ("system") and password ("manager"). The connection attempt fails with the broker showing  "Invalid message encoding" in its debug log. I can connect, though, when using another client (MQTT.fx). 

Using Wireshark, I looked at the connect packets of both clients and could see that MQTT.fx sends the password UTF8 encoded (the length is prepended) but the MQTT-Client does not encode the password as UTF8 (the length bytes are missing):

<img width="609" alt="mqtt fx" src="https://user-images.githubusercontent.com/7075830/100944357-68884d00-34ff-11eb-90ad-2223368b81a1.png">

<img width="609" alt="mqtt-client" src="https://user-images.githubusercontent.com/7075830/100944365-6d4d0100-34ff-11eb-910d-2e9755308e27.png">

Looking at http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/MQTT_V3.1_Protocol_Specific.pdf on page 17, this document says that the password "is the next UTF8 encoded string".

I modified `Create CONNECT Packet.vi` to send the password also UTF8 encoded, and now the connection does work with my broker:
<img width="1246" alt="Create Connect Packet" src="https://user-images.githubusercontent.com/7075830/100944839-5eb31980-3500-11eb-93a3-05ca3334eae0.png">

**Comment by francois-normandin** [comment]
@joerghampel thanks for the detailed report.
It looks like the server you connect to is requiring a UTF8 encoded password, but the normative requirement for password does not reference any encoding. Passwords can be any binary data, regardless of encoding. That is to allow for encrypted passwords to be supplied through an upgraded protocol.

The MQTT protocol standard I'm following is found here:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718031

You can see in section 3.5.1.5 that no encoding is specified, so this requirement is a particularity of the server ActiveMQ you are connecting to. 

I'm very much interested in understanding the differences of the major MQTT servers out there, so I can improve ease of use of the LVOS MQTT client. There could be a constructor made especially for each broker to ensure full compatibility with the extra requirements of those brokers. 

In this case, I'll check to find a way to inject a password encoding into the constructor. It might require that we override the client with a specific client for ActiveMQ. I'm sure other brokers will have similar behavior, so definitely a thing I'll investigate right away.

I gather you have a satisfying workaround for now. I'll keep you posted!

**Comment by joerghampel** [comment]
After reading your comment and the linked document, I now better understand the problem: It's not that the password has to be UTF8 encoded, but it needs to be prepended by two bytes containing its length:

>The Password field contains 0 to 65535 bytes of binary data prefixed with a two byte length field which indicates the number of bytes used by the binary data (it does not include the two bytes taken up by the length field itself).

So maybe this is a bug in the LVOS client after all?

**Comment by francois-normandin** [comment]
Yes, it is supposed to contain two bytes and then the password itself. I see what you mean. The utf8 node prepends those two bytes while not altering the characters which were already utf8 compliant, so I can see why it would work after you've introduced the node.
I'll confirm with code today and provide a fix quickly.

Thanks @joerghampel

**Comment by francois-normandin** [comment]
I've extended the node to bypass UTF8 encoding and applied it to password field.
You should see a MQTT Control Packet update later today on VIPM Community.

![image](https://user-images.githubusercontent.com/11728548/101020360-62fd2800-353c-11eb-998d-32ebc79ee941.png)

![image](https://user-images.githubusercontent.com/11728548/101020396-73ad9e00-353c-11eb-9226-a9516c1a1495.png)

For the record **(on the importance of complete Unit Testing**), here was the unit tests on the Connect packet:
![image](https://user-images.githubusercontent.com/11728548/101020733-f0d91300-353c-11eb-9685-d41178f3a0e1.png)

**Comment by francois-normandin** [comment]
Additional tests all pass.
![image](https://user-images.githubusercontent.com/11728548/101021454-ef5c1a80-353d-11eb-973e-4c1925b4be21.png)

**Comment by francois-normandin** [comment]
Package will be uploaded to VIPM Community and should appear shortly in your stream.
The release can be found here for immediate download:
https://github.com/LabVIEW-Open-Source/LV-MQTT-Control-Packets/releases/tag/3.1.3

**Comment by joerghampel** [comment]
Fantastic, thank you so much!
