### ISSUE TITLE
Missing Wire in DropVI_SimpleClientSubscriber

### ISSUE THREAD

**Issue by rfporter** [LabVIEW-Open-Source/MQTT-Client#6]
There is a missing wire in DropVI_SimpleClientSubscriber that causes it to fail when receiving a publish message.

![Capture](https://user-images.githubusercontent.com/6878763/109260630-7d0d7600-77cc-11eb-96f1-082bc061fc7f.PNG)

The publish message just needs to be wired to the Decode Application Message vi.

**Comment by francois-normandin** [comment]
This is fixed in the next release 3.1.6.
Thanks @rfporter
